Content-Centric Networking in C: include/ccn/sockaddrutil.h File Reference
sockaddrutil.h File Reference
sockaddr utilities
Functions
int ccn_charbuf_append_sockaddr (struct ccn_charbuf *, const struct sockaddr *)
Append a printable representation of sa (sans any port info) to the charbuf.
Detailed Description
sockaddr utilities
Part of the CCNx C Library.
Copyright (C) 2010 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file sockaddrutil.h.
Function Documentation
int ccn_charbuf_append_sockaddr (struct ccn_charbuf * c, const struct sockaddr * sa)
Append a printable representation of sa (sans any port info) to the charbuf.
IPv6 addresses will be enclosed in square braces, as in the host part of a URI.
Returns:
the port number (0 if no port number is available), or -1 for in case of an error.
Definition at line 38 of file ccn_sockaddrutil.c.
Referenced by collect_faces_html(), collect_faces_xml(), and post_face_notice().