Content-Centric Networking in C: cmd/ccnsimplecat.c File Reference
ccnsimplecat.c File Reference
Reads streams at the given CCNx URIs and writes to stdout.
Functions
static void usage (const char *progname)
Provide usage hints for the program and then exit with a non-zero status.
struct ccn_charbuf * make_template (struct mydata *md, struct ccn_upcall_info *info)
Construct a template suitable for use with ccn_express_interest indicating at least one suffix component, and stale data if so requested.
enum ccn_upcall_res incoming_content (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
Handle the incoming content messages.
int main (int argc, char **argv)
Process options and then loop through command line CCNx URIs retrieving the data and writing it to stdout.
Detailed Description
Reads streams at the given CCNx URIs and writes to stdout.
A CCNx command-line utility.
Copyright (C) 2009-2011 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccnsimplecat.c.
Function Documentation
enum ccn_upcall_res incoming_content (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info)
Handle the incoming content messages.
Extracts the data, and requests the next block in sequence if the received block was not the final one.
Definition at line 80 of file ccnsimplecat.c.
Referenced by ccn_dump_names(), main(), and split_my_excludes().
int main (int argc, char ** argv)
Process options and then loop through command line CCNx URIs retrieving the data and writing it to stdout.
Definition at line 184 of file ccnsimplecat.c.
struct ccn_charbuf* make_template (struct mydata * md, struct ccn_upcall_info * info) [read]
Construct a template suitable for use with ccn_express_interest indicating at least one suffix component, and stale data if so requested.
Definition at line 55 of file ccnsimplecat.c.
static void usage (const char * progname) [static]
Provide usage hints for the program and then exit with a non-zero status.
Definition at line 33 of file ccnsimplecat.c.