.TH "ccnd/ Directory Reference" 3 "14 Sep 2011" "Version 0.4.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccnd/ Directory Reference \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBandroid_main.c\fP"
.br
.ti -1c
.RI "file \fBandroid_msg.c\fP"
.br
.ti -1c
.RI "file \fBccnd.c\fP"
.br
.ti -1c
.RI "file \fBccnd_internal_client.c\fP"
.br
.RI "\fIInternal client of ccnd, handles requests for inspecting and controlling operation of the ccnd; requests and responses themselves use ccn protocols. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBccnd_main.c\fP"
.br
.RI "\fIA CCNx program. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBccnd_msg.c\fP"
.br
.RI "\fILogging support for ccnd. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBccnd_private.h\fP"
.br
.RI "\fIPrivate definitions for ccnd - the CCNx daemon. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBccnd_stats.c\fP"
.br
.RI "\fIStatistics presentation for ccnd. \fP"
.PP
.in +1c

.ti -1c
.RI "file \fBccndsmoketest.c\fP"
.br
.RI "\fISimple program for smoke-test of ccnd. \fP"
.PP

.in -1c
